package com.springgrpc.server.domain.enums; 
public enum ErrorCode { 
    INVALID_CREDENTIALS, INVALID_CLIENT, INVALID_GRANT, INVALID_SCOPE, 
    INVALID_TOKEN, EXPIRED_TOKEN, REVOKED_TOKEN, INSUFFICIENT_SCOPE, 
    USER_NOT_FOUND, USER_LOCKED, USER_INACTIVE, INTERNAL_ERROR 
} 
